# Plugins
plugins:
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss
overrides:
  - files: "*.astro"
    options:
      parser: astro

# Plugin options
astroAllowShorthand: true
astroSkipFrontmatter: false

# Tailwind options
tailwindStylesheet: "./src/style/global.css"
tailwindAttributes: []
tailwindFunctions: []
tailwindPreserveWhitespace: false
tailwindPreserveDuplicates: false

# Main options
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
objectWrap: preserve
bracketSameLine: false
arrowParens: always
rangeStart: 0
rangeEnd: -1
requirePragma: false
insertPragma: false
proseWrap: always
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
